### ISSUE TITLE
Track new rules

### ISSUE THREAD

**Issue by cjihrig** [cjihrig/belly-button#28]
- ~~https://eslint.org/docs/rules/array-callback-return (v2.0.0) (not taken, see known limitation)~~
- ~~http://eslint.org/docs/rules/getter-return (v4.2.0)~~
- ~~https://eslint.org/docs/rules/implicit-arrow-linebreak (v4.12.0) (not needed)~~
- ~~https://eslint.org/docs/rules/no-var (v0.12.0)~~
- ~~https://eslint.org/docs/rules/eol-last (v0.7.1) (already present)~~
- ~~https://eslint.org/docs/rules/no-buffer-constructor (v4.0.0) (already present)~~
- ~~https://eslint.org/docs/rules/prefer-rest-params (v2.0.0)~~
- ~~https://eslint.org/docs/rules/prefer-spread (v1.0.0)~~
- ~~https://eslint.org/docs/rules/no-async-promise-executor (v5.3.0)~~
- ~~https://eslint.org/docs/rules/require-atomic-updates (v5.3.0)~~
- ~~https://eslint.org/docs/rules/no-misleading-character-class (v5.3.0)~~

[ESLint 5.x.x migration guide](https://eslint.org/docs/5.0.0/user-guide/migrating-to-5.0.0)

**Comment by geek** [comment]
Need to also add the following:
- https://eslint.org/docs/rules/object-curly-spacing
- https://eslint.org/docs/rules/array-bracket-spacing
